### PR TITLE
Fix installation of themes

### PR DESCRIPTION
**Pull request by kasbah**
My best guess as to what it should be.

### CODE REVIEW

**Comment by falkTX** [comment]
bin/styles should be automatically created when the styles are built.
is it empty for you?

**Comment by kasbah** [comment]
It is yeah, even after `make`. Just doing another pull request with build instructions. Maybe you could point me to what I am missing?

**Comment by falkTX** [comment]
You're probably missing the headers for Qt.
The theme is c++ code, not python.

**Comment by kasbah** [comment]
Well, I am not looking to package anyway so I was barking up the wrong tree with this.

**Pull request closed without merging**
