### PR TITLE
New native plugin for forcing all midi to a particular channel

### PR DESCRIPTION
**Pull request by bencrossman**

### CODE REVIEW

**Comment by falkTX** [comment]
Please target the PR against develop, master is "closed" for the upcoming stable 2.0 release.

**Comment by bencrossman** [comment]
> Please target the PR against develop, master is "closed" for the upcoming stable 2.0 release.

Done

**Comment by falkTX** [comment]
Cool, thanks again.
I will wait till CI finishes and then merge if all is okay.

Funny how there are now some plugins in the codebase I never coded myself but have me as the author :joy: 
But it's all good, no worries.

**Comment by bencrossman** [comment]
> Cool, thanks again.
> I will wait till CI finishes and then merge if all is okay.
> 
> Funny how there are now some plugins in the codebase I never coded myself but have me as the author 😂
> But it's all good, no worries.

Sure

Yeah but even though it's a trivial plugin, it is really handy in the Windows build where we can't at the moment do multiple out ports on a plugin like we can with Linux JACK.

**Comment by falkTX** [comment]
Yeah, that is understandable.
Have you looked into http://x42-plugins.com/x42/x42-midifilter ?
The author publishes windows builds, which should work fine in carla.

**Comment by bencrossman** [comment]
> Yeah, that is understandable.
> Have you looked into http://x42-plugins.com/x42/x42-midifilter ?
> The author publishes windows builds, which should work fine in carla.

I've seen lots of midi plugin collections but haven't seen a LV2 one before.
Thanks for the link.

**Pull request merged**
