### PR TITLE
Add the frontend translation mechanism

### PR DESCRIPTION
**Pull request by jpcima**
#596
This adds the mechanism to build, install, load Qt translations into the frontend.

The desired language code is added to `I18N_LANGUAGES`. (example `fr_FR`)
This is the behavior to expect:
1. an initial `make` commands scans sources, creates `.ts` files (`pylupdate5` step)
2. the default build rule will generate `.qm` files
3. installing will copy `.qm` into `resources/translations`

Please note: no translation is included, nor is there a plan to add one shortly after this.
This is to help the job of translators to produce and maintain a custom translation of their making, like LibraZiK does.

### CODE REVIEW

**Comment by falkTX** [comment]
Niice, you saved me a lot of work!

I won't merge this just now, as it is not a feature I want to support in v2.1
But after v2.0.0 is announced and branches get switched around (master will be incoming v2.1, and develop v2.2/next), then I will merge this in there.

There are a lot of special things in the makefile though.
Do you know if these will work on non-gnu systems? (like FreeBSD and MacOS)

**Comment by jpcima** [comment]
>There are a lot of special things in the makefile though.
Do you know if these will work on non-gnu systems? (like FreeBSD and MacOS)

This would have to be checked, as I don't have familiarity with either of these Make systems.
I have tried only GNU/Linux.

**Comment by jpcima** [comment]
I have had success on FreeBSD12 and macOS 10.12.

I'm revising the code in just a minor way: for the Qt part of translations, aka `qt_*.qm` files, I will perform in order the 2 loading attempts: 1. the case these files are shipped as carla resource, and 2. the case they are present in the Qt distribution.
This will allow macOS i18n support in two cases, the one of an app bundle, or a `make install` build from the sources.

About FreeBSD, I built with the tool GNU make `gmake`.
BSD make did not work in any case, whether with or without the translation work.

**Comment by jpcima** [comment]
Rebased on `develop`, conflicts resolved

**Comment by trebmuh** [comment]
Just mentioning. Note that, I've got one translation ready for French. No hurries but so you know.

**Comment by falkTX** [comment]
Changes have been merged to develop branch. Scheduled for whenever 2.3 releases

**Comment by falkTX** [comment]
and of course, thanks!

**Pull request closed without merging**
