### PR TITLE
Revised attempt at: https://github.com/falkTX/Carla/pull/489

### PR DESCRIPTION
**Pull request by bencrossman**

### CODE REVIEW

**Comment by bencrossman** [comment]
Now that Carla 2.0 is out, can we merge this pull request?

Thanks

**Comment by falkTX** [comment]
yes, but now we really need to put this back in the juce class since it is back once again :)
sorry

**Comment by bencrossman** [comment]
ah great ok, will do that

**Comment by bencrossman** [comment]
Ok, think this is good now

**Comment by falkTX** [comment]
Sorry I got distracted and forgot about this.
It has been too long. Let's merge now and if there is an issue, we fix later.

**Comment by bencrossman** [comment]
Thank you, awesome

**Comment by jdarnell2** [comment]
I'm using a plugin, (Amplitube 5) that switches presets via Program Change messages.  How can I implement the above added feature into the latest version of Carla?  Do I have to rebuild and re-compile?  I'm using Windows 10 x64.

**Pull request merged**
