### PR TITLE
#332 Auto-configure WINEPREFIX by detecting VST DLL inside wine prefix

### PR DESCRIPTION
**Pull request by jypma**
Preliminary PR for #332 , to show the direction I'm taking. It seems to auto-load and set WINEPREFIX for 64-bit plugins just fine.

I'm having a little trouble getting anything 32-bit to load though.

### CODE REVIEW

**Comment by jypma** [comment]
A bit of recompiling later, I now have 64-bit Kontakt and 32-bit Massive running inside one Carla :)

(I own NI Komplete 7, and actually everything works 64-bit in Wine these days, _except_ for Massive. That's the most important reason I wanted this)

**Comment by falkTX** [comment]
For an initial version it seems fine, you should use juce File::exists() instead of calling platform-specific code though.
Also I'd prefer if "WINEPREFIX" was not being set if it already exists in the environment.
Lastly, we need to revert the previous "WINEPREFIX" env var when changing it.
(There's some class in carla utils for it..)

Anyway, if you leave it as it is, it's already enough for me to integrate it (just slightly modified).

**Comment by jypma** [comment]
Addressed (1) and (2). Looking into how to revert after done.

**Comment by jypma** [comment]
reverting WINEPREFIX is in now. Please re-check.

**Comment by falkTX** [comment]
Seems good now, I'll only have to adjust the coding style a bit.

**Comment by jypma** [comment]
Let me know what you'd like to have changed, I could try to patch it in. And consider having a `CONTRIBUTING.md` with your preferred coding style :-)

**Comment by jypma** [comment]
Causes https://github.com/falkTX/Carla/issues/378 ATM.

**Comment by jypma** [comment]
Fixed #378 .

**Comment by jypma** [comment]
@falkTX Is there anything I can do to help this PR get in?

**Comment by falkTX** [comment]
no, just keep pinging me from time to time so make this higher priority :)
I just need to get to it one day, soon.

**Comment by falkTX** [comment]
I didn't forget this pull request, I want this for the next beta.
Managing the wine prefixes is a pain.

I will add this after I add some wine options in carla's settings.
Want to do both things at the same time, as they fit together.
(ie, option to force a specific wine prefix, use env or try to find the correct one automatically. then also define the default wineprefix if the auto mode can't find one.)

**Comment by jypma** [comment]
Awesome!

On October 19, 2017 9:56:26 PM GMT+02:00, Filipe Coelho <notifications@github.com> wrote:
>Closed #374 via 68bd68b6f18b96d47a41ff60653a316c2001dd0b.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/falkTX/Carla/pull/374#event-1301820831

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Pull request closed without merging**
