### PR TITLE
patchcanvas: Size-tuned SVG icons

### PR DESCRIPTION
**Pull request by nick87720z**
I tuned some svg icons, used in patchcanvas, for better crispness. For now they are not tuned for specific size, and loading code in patchcanvas creates pixmaps of different sizes for some icons, seemingly bound to image sizes.

Some icons i made for 12px initially, but it seems, that most are scaled to 16px (at least icons for specific apps), so all i have touched - have 16px tuned copy. Original versions have 'ref' suffix (reference, to use for new size tunings). I only forgot to save unchanged version for Audacious. Default (unsuffixed) version is now 16px, and patchcanvas code is edited.

some icons don't seem to be different, like File icon...

Patchbay with new icons 1x:
patchcanvas-icons-scalable-1x
Scaled to max, to better show difference:
patchcanvas-icons-scalable-3x
Icons dir thumbnails:
patchcanvas-icons-scalable-dir

### CODE REVIEW

**Comment by falkTX** [comment]
Can you please reopen the PR against the new develop branch?
master is now frozen for stable releases, new stuff will go to develop first.
thanks.

**Comment by nick87720z** [comment]
ok, rebased

**Comment by falkTX** [comment]
> nick87720z wants to merge 1 commit into falkTX:master.
so still for master

**Comment by nick87720z** [comment]
fixed - forgot to edit base

**Comment by falkTX** [comment]
thanks!!

**Pull request merged**
